---
env:
  - GO111MODULE=on
dist: _output
builds:
  - binary: k8s-split
    main: ./cmd/k8s-split/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
